### ISSUE TITLE
schema.org markup needs to be optimized

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd#1]
*same as [vocabs uwlib-cams/uwlswd#9](https://github.com/uwlib-cams/uwlswd/issues/9)*

A quick check with the [Schema Markup Validator](https://validator.schema.org/) shows lots of room for improvement...

**Comment by briesenberg07** [comment]
Closed this unintentionally!?

**Comment by briesenberg07** [comment]
@gerontakos and @cspayne I mentioned the [Schema Markup Validator](https://validator.schema.org/) in our 2023-08-21 meeting - might help us assess our schema.org application profile

**Comment by cspayne** [comment]
current schema.org xsl scripts have been extensively tested with RDF/XML and DataCite XML files containing many different variations of information. 

Testing has ensured that:
- properties that may contain a single value or an array [ ] of values validate in either circumstance
- JSON-LD objects { } are set up properly (e.g. creator)
- missing values do not invalidate the whole markup 
- commas appear where they are supposed to
