### ISSUE TITLE
UWLSWD file-naming conventions

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd#2]
# CONVENTIONS FOR ~~VOCAB TITLES AND~~ FILE NAMES

- ~~Vocab titles are varied, for example, sometimes "University of Washington Libraries [...]" is included, sometimes "Linked Data Vocabularies: [...]" is included, etc.~~ (Address dataset titles in separate issues as needed, see [below](https://github.com/uwlib-cams/uwlswd_scripts/issues/2#issuecomment-1208535021))
- Vocabulary file names are inconsistent, for example, these are not constructed in the same way each time, and don't necessarily align with `dct:title` values

## QUESTIONS
- ~~Can we decide on any conventions for creating the vocabulary dct:title values? For example, will "University of Washington Libraries" (or "UWL", etc.) be included?~~ (Address dataset titles in separate issues as needed, see [below](https://github.com/uwlib-cams/uwlswd_scripts/issues/2#issuecomment-1208535021))
- Can we decide on any conventions for creating filenames for vocabulary serializations? For example, should these be constructed from dct:title values?

## AT PRESENT
| DOI | dct:title | filename **[1]** | 
|---|---|---|
| https://doi.org/10.6069/uwlib.55.b.1 | Linked Data Platform Vocabulary | `platformVocab` |
| https://doi.org/10.6069/uwlib.55.b.2 | RDF Vocabulary for Linked Data Processes | `reconVocab` |
| https://doi.org/10.6069/uwlib.55.b.3 | Linked Data Vocabularies: Children's Literature Categories | `ChildrensLitCategories` |
| https://doi.org/10.6069/uwlib.55.d.1 | University of Washington Libraries rdfs:Class Definitions | `classes_local` |
| https://doi.org/10.6069/uwlib.55.d.2 | Linked Data Platforms | `platforms` |
| https://doi.org/10.6069/uwlib.55.d.3 | University of Washington Libraries rdf:Property Definitions | `properties_local` |
| https://doi.org/10.6069/uwlib.55.d.4 | University of Washington Libraries RDA Application Profile Extension | `rdaApplicationProfileExtension` |
| https://doi.org/10.6069/uwlib.55.d.5 | Newspaper Genre List | `newspaperGenreList` |

### NOTES
1. In addition to filenames given in tables, filenames for all but HTML+RDFa serialiations include a hyphen + version number (i.e. `-1-0-1`) and, of course, a filename extension (.html, .ttl, .rdf, .nt, .json/.jsonld). So, for example, `platformVocab-1-0-1.ttl`

CC 2022-07-27 meeting participants
@gerontakos @CECSpecialistI @AdamSchiff @junghaelee @JianPLee @pan-zhuo @mcm104

**Comment by briesenberg07** [comment]
# PROPOSAL: FILE NAMING CONVENTION

The simplest rule for creating file names may be the best. Something like:
- Use dct:title values as file names, with the following rules:
   - Preserve capitalization as in dct:title values
   - Substitute the following characters with an underscore: `:`, ` ` (space)
   - Remove the following characters: `'`
- Add additional rules (for example, additional character-substitution rules) only as needed

## PROS
- Generate file names from dataset dct:title values programmatically fairly easily
- Allow humans to anticipate file names fairly easily

## CONS
- The convention does nothing to ensure unique file names, this will depend on having unique (at least, locally unique) dataset titles
- Does nothing to shorten lengthy dataset titles; entering lengthy file names may be inconvenient

## NOTE
- I think that dataset titles (dct:title values for each DOI resource) should be discussed separately; let's use distinct issues to discuss changing dataset titles as needed.

## EXAMPLES
For *existing dct:title values*, this would give us:
| dct:title | existing filename | proposed new filename |
|---|---|---|
| Linked Data Platform Vocabulary | `platformVocab` | `Linked_Data_Platform_Vocabulary` |
| RDF Vocabulary for Linked Data Processes | `reconVocab` | `RDF_Vocabulary_for_Linked_Data_Processes` |
| Linked Data Vocabularies: Children's Literature Categories | `ChildrensLitCategories` | `Linked_Data_Vocabularies_Childrens_Literature_Categories` |
| University of Washington Libraries rdfs:Class Definitions | `classes_local` | `University_of_Washington_Libraries_rdfs_Class_Definitions` |
| Linked Data Platforms | `platforms` | `Linked_Data_Platforms` |
| University of Washington Libraries rdf:Property Definitions | `properties_local` | `University_of_Washington_Libraries_rdf_Property_Definitions` |
| University of Washington Libraries RDA Application Profile Extension | `rdaApplicationProfileExtension` | `University_of_Washington_Libraries_RDA_Application_Profile_Extension` |
| Newspaper Genre List | `newspaperGenreList` | `Newspaper_Genre_List` |

**Comment by briesenberg07** [comment]
TO DO: Add file-naming convention to uwlswd wiki, close issue

**Comment by briesenberg07** [comment]
Hello @gerontakos 
I created a wiki and added a [file-naming conventions page](https://github.com/uwlib-cams/uwlswd/wiki/file_naming_conventions) which reflects the proposal here. Once you've had a chance to review I will close this issue.
This does not provide any guidance for actually naming our datasets, which is probably a tougher question.

**Comment by CECSpecialistI** [comment]
I love it and fully endorse these file naming conventions.
