### ISSUE TITLE
standardize and document schema.org markup

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/uwlswd#23]
currently, schema.org markup appears slightly differently in many rdf2rdfa scripts. Is this something we can standardize?
current draft: [schemaOrgMarkup-draft.xsl](https://github.com/uwlib-cams/uwlswd/blob/main/xsl/schemaOrgMarkup-draft.xsl)

# @briesenberg07 comment:
Thank you @cspayne! We need to standardize this

**Comment by briesenberg07** [comment]
This commit ^^ isn't really to do with this issue

**Comment by briesenberg07** [comment]
Places where our schema markup is defined:
- [rdfxml-datacite-schema.csv](https://github.com/uwlib-cams/uwlswd/blob/main/rdfxml-datacite-schema.csv) -- see column **"schema.org in HTML+RDFa web document (...)**	
- [dc2schemaorg.xsl](https://github.com/uwlib-cams/uwlswd/blob/main/xsl/dc2schemaorg.xsl)
- [rdf2schemaorg.xsl](https://github.com/uwlib-cams/uwlswd/blob/main/xsl/rdf2schemaorg.xsl)
