### ISSUE TITLE
standardize DataCite metadata across datasets/vocabs

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/uwlswd#25]
Related resource = [rdfxml-datacite-schema.org mapping spreadsheet](https://docs.google.com/spreadsheets/d/1jKYPFzhE_iNsqrekX696_wFehq9NTM4v212J41jGv0s/edit?usp=sharing)

**Comment by gerontakos** [comment]
This will change depending on whether or not we derive the DataCite XML from the RDF/XML.

**Comment by cspayne** [comment]
From my understanding, we want the DataCite XML to match the RDF/XML (in regards to title and description)

**Comment by gerontakos** [comment]
Match as well as they can, yes, but do we want to process the RDF/XML to output the Datacite, produce the DataCite manually, or something else. To concretize this, our MARC vocabularies -- we have over 100 -- are being prepared to publish. I wrote some code to process the RDF/XML and output the DataCite XML. Is tha something we plan to buld into the workflow? Currently we produce both manually.

**Comment by cspayne** [comment]
This may be useful at some point: https://support.datacite.org/docs/api-create-dois

**Comment by cspayne** [comment]
> Match as well as they can, yes, but do we want to process the RDF/XML to output the Datacite, produce the DataCite manually, or something else. To concretize this, our MARC vocabularies -- we have over 100 -- are being prepared to publish. I wrote some code to process the RDF/XML and output the DataCite XML. Is tha something we plan to buld into the workflow? Currently we produce both manually.

Looking at the RDF/XML, there are some elements required by the DataCite metadata schema that are not available (at least in uwlswd_vocabs and uwlswd_datasets). 
To use a transformation we would need to require the following to be included within the RDF/XML or as a fixed value within the transformation stylesheet:

- Identifier
- **Creator** 
- Title
- **Publisher**
- **PublicationYear** 
- ResourceType (with mandatory general type description subproperty)

_(as an aside, I discovered that PublicationYear is a required element, so we may want to stick with this instead of the date element which we had discussed using in the last meeting)_

**Comment by gerontakos** [comment]
Creative solution needed to handle repeating fields in Datacite, like multiple contributors; in "flat rdf/xml," we cannot pair statements about entities that are triple-objects. Like how will we structure the rdf/xml to output, in the Datacite XML, contributor/contributorName and contributor/contributorIdentifier ? Of course we could use bnodes.

**Comment by gerontakos** [comment]
How will we structure the RDF/XML? Do we have flexibility? For example, do we have to structure it as follows:
<rdf:Description rdf:about="IRI">
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>
    <dct:title>Title of Concept Scheme</dct:title>
</rdf:Description>

...or can we do the following as well:
<skos:ConceptScheme rdf:about="IRI">
      <dct:title>Title of Concept Scheme</dct:title>
</skos:ConceptScheme>

**Comment by cspayne** [comment]
> How will we structure the RDF/XML? Do we have flexibility? For example, do we have to structure it as follows:
> 
> ```
> <rdf:Description rdf:about="IRI">
>     <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>
>     <dct:title>Title of Concept Scheme</dct:title>
> </rdf:Description>
> ```
> 
> ...or can we do the following as well:
> 
> ```
> <skos:ConceptScheme rdf:about="IRI">
>       <dct:title>Title of Concept Scheme</dct:title>
> </skos:ConceptScheme>
> ```

@gerontakos 

The current workflow only supports the first structure! That is, an rdf:Description element with an rdf:about attribute and sub-elements, including rdf:type

**Comment by briesenberg07** [comment]
@gerontakos is it possible to provide examples of the DataCite XML that you wish to output, to do which (I think), you state that the following RDF/XML structure would be required in source data?

```
<skos:ConceptScheme rdf:about="IRI">
      <dct:title>Title of Concept Scheme</dct:title>
</skos:ConceptScheme>
``` 

I'm having trouble understanding what DataCite XML couldn't be output from the RDF/XML structure that @cspayne 's workflow accommodates, that is:

```
<rdf:Description rdf:about="IRI">
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>
    <dct:title>Title of Concept Scheme</dct:title>
</rdf:Description>
```

**Comment by gerontakos** [comment]
I was only wondering if we could use either format. The answer is only one format is accommodated at present, and that's fine. And the DataCite will output fine.

**Comment by gerontakos** [comment]
Creative solution needed for minting DOIs. At present, the DOI needs to be in the RDF/XML. However, at the time the DOI is created, neither the HTML/RDFa nor the DataCite XML metadata is created. As a result, we cannot complete the DOI registration: we don't have a URL (for the HTML) and we don't have metadata (for DataCite). So we need a solution for this. Currently we are doing it manually: create the draft DOI, insert in the RDF/XML, run the workflow scripts, the RDF/XML derivatives all contain the proper DOI, and the derivatives will be used to complete the DOI (manually), entering (in DataCite) the URL of the HTML and uploading the DataCite XML stored in uwlswd/DataCite. That's pretty clunky.

**Comment by cspayne** [comment]
We have made significant progress using the [rdfxml-datacite-schema.org stylesheet](https://docs.google.com/spreadsheets/d/1jKYPFzhE_iNsqrekX696_wFehq9NTM4v212J41jGv0s/edit?usp=sharing) resulting in [rdf2datacite.xsl](https://github.com/uwlib-cams/uwlswd/blob/main/xsl/rdf2datacite.xsl) which has been incorporated into the workflow. 
I am closing this big issue, with the idea that we will create smaller issues to discuss potential changes/additions to this workflow now that it is set up.
