### ISSUE TITLE
merge uwlswd + uwlswd_metadata

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd#31]
**SUMMARY**

QUESTION ❓ *Merge repositories [uwlswd](https://github.com/uwlib-cams/uwlswd) and [uwlswd_metadata](https://github.com/uwlib-cams/uwlswd_metadata)?*

**DETAILS**

UWLSWD resources and publishing tools are spread across several repositories (see [uwlswd/repositories](https://github.com/orgs/uwlib-cams/teams/uwlswd/repositories) for details). As a result it is often difficult to decide which repository an issue or discussion should be created in. 

Merging these two repositories *might* make these decisions easier. That is:
- for any issue or discussion affecting all/multiple UWLSWD resources, the new merged repo should be used
- for any issue or discussion specific to a given resource (dataset/vocab), the repo containing the resource serializations should be used

*~Seeking~ Received feedback from @uwlib-cams/uwlswd members*

**@briesenberg07 to-dos**

- [x] Transfer any issues and discussions from uwlswd_metadata to here
- [x] Determine file/folder structure for uwlswd to incorporate DataCite metadata files
- [x] Combine the two repositories ~~in a way which preserves commit history for uwlswd_metadata files~~
- [x] Make any needed changes to uwlswd.wiki (change links to uwlswd_metadata, etc.)
- [x] Following confirmation that commit history in the previous remote (uwlswd_metadata) is not needed, delete it

**Comment by gerontakos** [comment]
It seems OK. The trick, I believe, is to actually "merge" and not "move" so as to retain the commit history. I've never merged two repos. This is a little more advanced git so maybe we can do it at a git meeting? (We had something else for a Git meeting, I can't remember what.)

**Comment by cspayne** [comment]
This would actually be quite helpful! It shouldn't cause any problems in the workflow.

**Comment by briesenberg07** [comment]
*Combined repositories* 🎉 *lost commit history* 😢 *(or, at least, commit history that can be viewed easily in the browser)*

See details of the attempt at Sandbox/[combine-repos-attempt-20230815](https://github.com/uwlib-cams/Sandbox/tree/master/combine-repos-attempt-20230815)

The very minimal commit history for DataCite metadata files is still available, for the moment, [at that repository](https://github.com/uwlib-cams/uwlswd_metadata/commits/main). But, @gerontakos , @cspayne , any reason not to delete the old repo and complete [the tasks above](https://github.com/uwlib-cams/uwlswd/issues/31#issue-1844043235)?

**Comment by cspayne** [comment]
I don't see any potential issues on my end!

**Comment by briesenberg07** [comment]
Done - DataCite XML in `uwlswd/DataCite`, uwlswd_metadata deleted
