### ISSUE TITLE
In the UWLSWD workflow, will we derive uwlswd metadata from the RDF/XML dataset's description of itself? This decision effects our local DataCite requirements.

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/uwlswd#33]

**Comment by gerontakos** [comment]
Refer to issue #25

**Comment by briesenberg07** [comment]
Even though this has been closed, I don't think that the question...

> **In the UWLSWD workflow, will we derive uwlswd metadata from the RDF/XML dataset's description of itself?** 

...was answered.

I believe that the answer is yes, and that we are discussing how to build this conversion into the workflow in #40 . @gerontakos @cspayne is this correct?
