### ISSUE TITLE
html improvements

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/uwlswd#41]
- [x] ensure rdfa meets specifications and standards
- [x] create css file to format table and any other aesthetic properties of web page
- [x] accessibility

**Comment by cspayne** [comment]
validators:
https://validator.w3.org/nu/ (works with .xhtml)
http://linter.structured-data.org/

**Comment by cspayne** [comment]
@briesenberg07 @gerontakos 
I just pushed [uwlswd_vocabs/linked_data_platforms.html](https://github.com/uwlib-cams/uwlswd_vocabs/blob/main/linked_data_platforms.html) with these changes set up so they are visible [on the live site](https://uwlib-cams.github.io/uwlswd_vocabs/linked_data_platforms). 

[linked_data_platforms.rdf](https://github.com/uwlib-cams/uwlswd_vocabs/blob/main/linked_data_platforms.rdf) now reflects the rdflib style as well.

Let me know if you have any feedback, comments, or concerns!

**Comment by briesenberg07** [comment]
🎉 🎉  Wowow looking great! A nice update to the presentation IMHO!  

I'd like to talk about how to handle b-nodes in the HTML+RDFa presentation. I've thought about a couple of options:

- Present bnode near related data: Potentially problematic; what if the same bnode is referenced in multiple places--where to put it in the table?
- Present bnode objects in table as links to bnode subjects in the table: Seems do-able; if same bnode is referenced multiple times in table, each reference could link to the bnode description's anchor in table

**Comment by gerontakos** [comment]
Most certainly improved, thank you. However, it's still an ugly data table. Can we dress it up, put on some jewelry maybe, even tattoos? Something. What can we do? A data table is not uncommon, right? Is there another way to represent it? Maybe colors would make it more appealing? Make it seem like "serious data" or something?

Maybe we could also offer something less linear, some kind of visualizations? That wouldn't be in place of this data but in-addition-to.

I'm not particular about bnode representation; however, the bnode in this dataset is flat-out wrong. There's no partition. "Let us be forgiving of the mistakes we make."

Also, what in heaven is a "platform"?

**Comment by gerontakos** [comment]
the RDF/XML is much easier to read and, I expect, easier to process.

**Comment by cspayne** [comment]
see [test_format.html](https://uwlib-cams.github.io/uwlswd_vocabs/test_format)

**Comment by gerontakos** [comment]
Nice! The links above the table -- are they now redundant and unnecessary?

**Comment by cspayne** [comment]
> Nice! The links above the table -- are they now redundant and unnecessary?

They aren't redundant quite yet! I may try to move them so they appear under the tab displaying that format, but if anyone wants to download and use those files, the links will still be useful.
