### ISSUE TITLE
favicon for uwlswd pages

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd#46]
uwlib-mig and uwlib-cams pages use favicons (see webviews/[images](https://github.com/uwlib-cams/webviews/tree/master/images)) obtained from Wikimedia Commons (with open/CCZero licenses). Add favicon for use in UWLSWD HTML.

**Comment by briesenberg07** [comment]
📰 THIS JUST IN...

RDF logo in the public domain??? See Wikimedia Commons > File:Rdf logo.svg > [Licensing](https://commons.wikimedia.org/wiki/File:Rdf_logo.svg#licensing)

(*Needs further investigation...*)

**Comment by briesenberg07** [comment]
See also:
- [W3C Semantic Web Logos and Policies](https://www.w3.org/2007/10/sw-logos.html)
- [W3C RDF Resource Description Framework Icons](https://www.w3.org/RDF/icons/) -- looks as if the triple icon seen at the Wikimedia Commons link above has been deprecated by the W3C in favor of the new cube designs at link above

**Comment by cspayne** [comment]
Looking at the policies for the W3C Semantic Web Logo, I believe we would be allowed to use something like this:
`<link href="https://www.w3.org/Icons/SW/sw-cube.png" alt="W3C Semantic Web Logo" rel="icon" type="image/png">`

**Comment by briesenberg07** [comment]
I propose sticking with the CAMS favicon, which [is from Wikimedia Commons](https://uwnetid.sharepoint.com/:t:/s/og_library_cams/EfqSc98PN3pHnkwkPJ0dCFoBgwZ29Uy8UYlH43f-pZ7_jQ?e=B6rHid) and was published without any restrictions, to avoid needing to 1) observe any attribution requirements for W3C icons and 2) determine whether we would be, by using the W3C icon, asserting that our data meets certain requirements.

```

<link rel="icon" type="image/png"
                        href="https://uwlib-cams.github.io/webviews/images/book.png"/>
```
