### ISSUE TITLE
changing owl:versionInfo to schema:version in all UWLSWD resources

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/uwlswd#47]
We are making the switch to schema:version elements using schemaver.
Update: 

- [x] uwlswd_vocabs
- [x] uwlswd_datasets
- [x] uwlswd_marc_007
- [x] uwlswd_ngl

**Comment by cspayne** [comment]
Version update notes: 
- uwlswd_vocabs_marc_007 - resources do not use rdf:Description (and substitute dois include #)
- uwlswd_datasets - wait until metadata is moved to individual files

**Comment by gerontakos** [comment]
I've got the 007's; they're not completed data yet. I'll run the RDF/XML through a "final prep" which will include adding schema:version = 1-0-0.

I just did the NGL change to the RDF/XML. The RDF/XML is ready to go. I will put it through the serialization process (the "workflow" (what should we call it?)) next week.
