### ISSUE TITLE
move xslt for NGL files out of uwlswd/legacy and into their own directory undr uwlswd\

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/uwlswd#54]
xml2html-newspaperGenreList.xsl and xml2html-newspaperGenreList.xsl should be moved out of legacy and into, say, uwlswd\xsl\ngl. Paths can be changed as well in those files.

**Comment by briesenberg07** [comment]
Just put in xsl/ ? Don't know why they couldn't go there.

**Comment by cspayne** [comment]
marcxml2rdfxml.xsl and xml2html-newspaperGenreList.xsl are now in uwlswd/xsl/

**Comment by briesenberg07** [comment]
tagging @gerontakos to be sure he knows where marcxml2rdfxml.xsl and xml2html-newspaperGenreList.xsl are when these are needed--in **uwlswd/xsl/**

**Comment by gerontakos** [comment]
Yes, thank you, xsl will be a good home for them.
