### ISSUE TITLE
schema.org namespace

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/uwlswd#55]
We should formalize, in our guidelines, that the namespace URI for schema.org is "http**s:**//schema.org/" and not "http://schema.org/" (both are acceptable).

**Comment by briesenberg07** [comment]
Hello @gerontakos I completely missed this until now. Is this done? Does this still need to be done? I don't know exactly where in the wiki the problem is.

**Comment by cspayne** [comment]
This info has been added to the guidelines > [step 6](https://github.com/uwlib-cams/uwlswd/wiki/01_resource_guidelines#step-6-use-standard-vocabularies)
