### ISSUE TITLE
dct:format

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/uwlswd#56]
I noticed that form_of_material.rdf contains `<dct:format rdf:resource="http://www.w3.org/ns/formats/RDF_XML"/>`.
Is this something that should change based on the serialization? (changing object value to http://www.w3.org/ns/formats/RDFa, http://www.w3.org/ns/formats/N-Triples, http://www.w3.org/ns/formats/Turtle, http://www.w3.org/ns/formats/JSON-LD depending on the format)

**Comment by briesenberg07** [comment]
Discussion 2023-09-28:

DCMI has definition:  
> The file format, physical medium, or dimensions of the resource.

What is the 'resource'? TG asserts that the resource is the manifestation. Therefore, dct:format value should change for each serialization.

**Comment by cspayne** [comment]
still need to update html-rdfa
