### ISSUE TITLE
Relationships to agents

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/uwlswd#59]
### Discussed in https://github.com/uwlib-cams/uwlswd/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **briesenberg07** September 18, 2023</sup>

## RDF/XML

- Use dct:creator / dct:contributor / dct:publisher with IRI value
- In the event that no IRI available for one of these agents, use dc:creator / dc:contributor / dc:publisher with literal value
- Observe BMR's made-up rule - N triples with dc/dct:creator = N creator agents, N triples with dc/dct:contributor = N contributor agents, and so on

## DataCite

- Use temporary 'mapping' to match IRI-to-literal for output to DataCite

## schema.org

- Use temporary 'mapping' to output IRIs and literals to schema.org

**Comment by cspayne** [comment]
### Some comments:
I can set up the xsl templates in such a way that we _can_ have both the literal and IRI in the RDF/XML (although this breaks BMR's proposed rule)
The templates have the rules as follows:
        - If an IRI is available, map to retrieve label
        - If a label is available and **NOT** in the map file, it does not have an associated IRI, use literal 

This means that 
1. agent IRIs must be added to the mapping file (uwlswd/xml/agents.xml) so we can retrieve literals
2. Both an IRI and a literal for the same agent _can_ be in the rdf/xml (whether we allow it is another thing, but it won't break the code)

**Comment by briesenberg07** [comment]
To do:

- [ ] Add [workflow requirements](https://github.com/uwlib-cams/uwlswd/issues/59#issuecomment-1739966308) above to wiki

**Comment by gerontakos** [comment]
For the record, I'm updating my guidelines for describing a concept scheme and stating that no matter what, and agent should be entered into agents.xml, whether you have the literal, the IRI, or both.

**Comment by cspayne** [comment]
> For the record, I'm updating my guidelines for describing a concept scheme and stating that no matter what, and agent should be entered into agents.xml, whether you have the literal, the IRI, or both.

Sounds good! I will update the xsl scripts accordingly.
