### ISSUE TITLE
add dct:description where missing for top-level resources

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd#60]
dct:description values are output as top-of-page text for HTML + RDFa, they may be used for the UWLSWD index page.

( To do: List top-level resources missing descriptions. )

**Comment by cspayne** [comment]
Some of the resources missing description values in the index, do have descriptions in the DataCite metadata files. 

However, temp_index.xsl only grabs datacite:description values with xml:lang = 'en-US'. 
`<description>{datacite:descriptions/datacite:description[@xml:lang = 'en-US']}</description>`

Not all of the datacite:description values have an xml:lang attribute, so they are not found during the transformation.

**Comment by briesenberg07** [comment]
PROPOSED PLAN OF ACTION:

- [ ] @briesenberg07 Update [temp_index.xsl](https://github.com/uwlib-cams/uwlswd/blob/479abea9ee39db6f6a20c1160496442c1d292c37/xsl/temp_index.xsl#L22) to grab *all* datacite:description values (we know, at this point, that all descriptions are English)
- [ ] @briesenberg07 @cspayne @gerontakos Prior to writing the new index.xsl (which will sort using schema:disambiguatingDescription), correct lang tags in DataCite XML

**Comment by briesenberg07** [comment]
Updated temp_index.xsl to fetch *all* datacite:description values, adding lang-tag to-dos to #65 . See also #26 .
