### ISSUE TITLE
Add BMPs to resources 

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/uwlswd#62]
Steps: 
1. add BMP to rdf/xml and update version 
2. run rdf2datacite.xsl
3. add any missing triples to rdf/xml based on rdf2datacite.xsl messages (use old DataCite metadata file for values)
4. re-run rdf2datacite.xsl and check output
5. run main.py to serialize 
6. push all to github
7. upload metadata file to DataCite

**Comment by cspayne** [comment]
see [resource type sheet](https://docs.google.com/spreadsheets/d/1jKYPFzhE_iNsqrekX696_wFehq9NTM4v212J41jGv0s/edit#gid=1330494801) for list of resources to be updated

**Comment by briesenberg07** [comment]
Once brief meaningful phrases (BMPs) are in place\*\*, we will want a new or updated stylesheet to output uwlswd/index.html. We can group by BMPs and output resource categories with lists and details, see [snapshot of index.xsl](https://github.com/uwlib-cams/uwlswd/blob/edf49adeab2e86a9d98c04738d8e4a7e915a07b4/xsl/index.xsl) for reference.

\*\* *In RDF/XML for top-level UWLSWD resources, BMPs will be `schema:disambiguatingDescription` values, in DataCite metadata, these will be `datacite:resourceType` values*

**Comment by cspayne** [comment]
Remaining resources to update:

- [ ] University of Washington Libraries' Semantic Web Data VoID Description of the Dataset 'University of Washington Libraries' Semantic Web Data'
- [ ] Newspaper Genre List

**Comment by cspayne** [comment]
Done!
