### ISSUE TITLE
Add starting version number to 07_versioning

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd#64]
Confirm with @gerontakos and @cspayne that this number, when first publishing a new resource, will be `1-0-0`.

See [this comment on 02_resource_workflow.md](https://hackmd.io/GAuTRhSVQuC0X_6KPafVSQ?comment=70a35aab-e8d5-4c3f-a801-880824d8f18a&utm_source=comment-card&utm_medium=icon)

**Comment by briesenberg07** [comment]
Note that filename for the wiki page on UWLSWD versioning may change soon, as pages 02 and 03 have been merged into 02

**Comment by cspayne** [comment]
> Confirm with @gerontakos and @cspayne that this number, when first publishing a new resource, will be `1-0-0`.

Yes, that's correct!
