### ISSUE TITLE
correct display label 'N-Triple' to 'N-Triples'

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd#67]
Label should align with the name used in [the spec](https://www.w3.org/TR/n-triples/), etc. -- 'N-Triples'

![image](https://github.com/uwlib-cams/uwlswd/assets/27664966/10e0efcd-7c0d-4809-bacc-b0ea714d417b)

**Comment by cspayne** [comment]
py file has been updated! Once resources are re-serialized, this will be fixed.
