### ISSUE TITLE
add missing lang tags

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd#72]
This is expected to require work for many published resources. Some of this work may be outside the scope of 'cleanup' because it requires some research. For example, what is the appropriate BCP-47 tag for Russian names in Latin script?

See also uwlib-cams/uwlswd_vocabs#30 .

Properties that should have lang tags: 
- rdfs:label 
- skos:prefLabel
- skos:definition
- schema:disambiguatingDescription
- dct:title
- dct:alternative
- dct:description
- dc:creator
- dc:publisher
- dc:contributor 
- any other properties with literal values values which could not be assigned a numeric datatype such as xsd:dateTime, xsd:decimal, etc.; that is, literal values with linguistic content

**Add/update list of resources to cleanup here:**

**Comment by cspayne** [comment]
@briesenberg07 
I added a list of properties that should have lang tags - does this seem accurate to you?

**Comment by briesenberg07** [comment]
I think it's a good list. The last bullet is a helpful catch-all, but we aren't talking about literal values like "2023-12-22" so I edited it to read:

> any other properties with literal values values which could not be assigned a numeric datatype such as xsd:dateTime, xsd:decimal, etc.; that is, literal values with linguistic content

**Comment by cspayne** [comment]
That makes sense!
As far as updating resources themselves - would it be better to make a complete list here, or make an issue per repository?

**Comment by briesenberg07** [comment]
Probably an issue per repo is better. Thank you!

**Comment by cspayne** [comment]
This is more of a conceptual question, but is including the dc:language property _and_ xml:lang attributes for each literal value containing linguistic content repetitive? Is there a purpose or reason that we include both?

**Comment by briesenberg07** [comment]
My understanding, such as it is:

```
<resource> dct:language "en" ;
   rdfs:label "a thing"@en ;
   dct:description "an information resource"@en .
```

`<resource> dct:language "en" .` indicates that the resource as a whole is... "in English", is an English-language resource. So this would indicate that human-readable data about the resource will be in English overall. 

Given this, it might seem repetitive to add language tags to each literal value, but I believe it's a good practice. 

Also, perhaps some resources are published in more than one language! In this case, literal values certainly need lang tags.

```
<resource> dct:language "en" , "ja" ;
   rdfs:label "a thing"@en ;
   rdfs:label "一つのこと"@ja ;
   dct:description "an information resource"@en ;
   dct:description "情報リソース"@ja .
```

**Comment by cspayne** [comment]
This has been split into individual issues per repository
