### ISSUE TITLE
cleanup remaining incorrect datacite:format values

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd#76]
See discussion https://github.com/uwlib-cams/uwlswd/discussions/75 - IANA media type for UWLSWD HTML+RDFa

At least two DataCite XML files still have incorrect `formats/format`:

- [x] uwlib.55.a.xml (incorrect format)
- [x] uwlib.55.d.5.xml (no format)

**Comment by cspayne** [comment]
Both now say text/html
