### ISSUE TITLE
update main.py components to use uwlsemanticweb as contact info

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd#82]
- [x] @briesenberg07 setup email service
- [x] @briesenberg07 let @cspayne know
- [x] @cspayne ... remaining steps...

**Comment by briesenberg07** [comment]
Finally set up shared email access-- details sent to @cspayne and @gerontakos via email.  
Let's switch UWLSWD contact email from tgis to uwlsemanticweb.

**Comment by cspayne** [comment]
@briesenberg07 
Just updated the xsl. 
I have a script that I can quickly run to just update the email address on each html page we already have that I can run as well if I have the go ahead.

**Comment by briesenberg07** [comment]
Hi @cspayne --  
Thank you! Yes please do run that script--that makes things very easy! Thank you!!

**Comment by cspayne** [comment]
Going to go ahead and close this issue - everything should be up to date!
