### ISSUE TITLE
requesting wiki enhancement

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/uwlswd#83]
Some observations on the document "02_resource_workflow", i.e. possible areas to edit (these are not questions I have but suggestions where areas of the procedure may be unclear)

Apologies for not just making the changes myself; I thought you'd like to do it

0. Setting up/Creating a repository branch
Some might prefer more explicit instructions on the branch setup than a reference to a GitHub document.

0. Setting up/Local repositories
"You'll need to clone..." may confuse someone if they've already cloned.
Maybe a link to UWLSWD (for clarification) in "You'll need to clone the UWLSWD repository"?

1. Create or update resources/New resources
"You will need this resource serialized as RDF/XML...." Pronoun "this" not clear.

2. Commit and push changes to the working file (RDF/XML)
It says commit and push but it's confusing if a branch was edited: push the branch alone? I could see someone asking, how do I do that?

4. Run main.py to serialize data/Running the script
"4. Whether to produce a simple HTML+RDFa file or..."
Most people probably won't know what to do, i.e. which option to choose.

"5. Commit and push..."
Might want to explain how to make a pull request.
Not clear about the pull request review, how it happens, then it says that the reviewer does not perform the merge, that I will?
It says "delete the remote and local branches" but that could be dangerous if some branches were created by others.

**Comment by cspayne** [comment]
@briesenberg07 

hackmd link: https://hackmd.io/@cspayne/H1lWmHl56/edit

**Comment by cspayne** [comment]
To do list based on @gerontakos' comments:

- [ ] 0. Setting up/Creating a repository branch
    - [ ] Add more explicit instructions on the branch setup than a reference to a GitHub document
- [ ] 1. Setting up/Local repositories
     - [ ] Clarify "You'll need to clone..."
     - [ ] Link to UWLSWD (for clarification) in "You'll need to clone the UWLSWD repository"?
- [ ] 2. Create or update resources/New resources
     - [ ] Clarify "You will need this resource serialized as RDF/XML...." Pronoun "this" not clear.
- [ ] 3. Commit and push changes to the working file (RDF/XML)
     - [ ] Clarify/add details: It says commit and push but it's confusing if a branch was edited: push the branch alone? I could see someone asking, how do I do that?
- [ ] 4. Run main.py to serialize data/Running the script
     - [ ] Clarify/add better instructions for fancy html 
- [ ] 5. Commit and push... 
     - [ ] explain how to make a pull request.
     - [ ] Clarify pull request instructions/who is doing what

**Comment by briesenberg07** [comment]
📢  Requesting review of updated UWLSWD wiki page '**02_resource_workflow**' - please see working document at HackMD **[2024_02_resource_workflow](https://hackmd.io/@ries07/SyeYKNTna/edit)**. 

Updated, approved doc will be published at https://github.com/uwlib-cams/uwlswd/wiki/02_resource_workflow .

**SUMMARY OF CHANGES:**

- '0. Setting up' > 'Local repositories' moved up
- '0. Setting up' > ;If updating a published resource\*, create a branch' expanded
- '6. Turn on or confirm GitHub pages settings for the repository' created
- '7. If updating a published resource, make and merge a pull request' expanded

Requesting review by @cspayne 
@gerontakos and @dkreisstomkins please also review and comment if you'd like

Editing requires sign-in to HackMD, you can sign in via GitHub

*Thank you!*

**Comment by briesenberg07** [comment]
Still to do @briesenberg07 - per [2024-02-26 meeting](https://docs.google.com/document/d/1fRrif3kHQV78rrrCdJdMlX-ax9HmUTVYaoFyhks_ApU/edit#bookmark=id.93igy679k0wn)

> copy-pasting filepaths to Saxon .jar, to files or directories for processing, may cause problems running main.py!

**Comment by briesenberg07** [comment]
Added warning about copy-pasting file paths to [working document for 02_resource_workflow](https://hackmd.io/@ries07/SyeYKNTna/edit). 

See **4. Run main.py to serialize data** > Running the script > asterisk (*) notes

**Comment by briesenberg07** [comment]
Published updated page 🎉
