### ISSUE TITLE
what to do with __pycache__ changes 

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/uwlswd#85]
@briesenberg07  @cspayne Probably should make an issue of this (minor issue, lots of words!).

Benjamin wrote, in email Sept 22, 2023: "py/__pycache__/ *should* be in the .gitignore for the UWLSWD repo. (.gitignore which is not itself ignored), so you should be able to leave your local files as they are, and they won't be committed or pushed."

So what do we do with that file? We either would want to do something akin to "delete" or we would want to add/commit in the local repo. I just added/committed to the local repo -- no harm there, right? -- but when I pushed, it was not ignored, despite having py/__pycache__/ in the .gitignore file. So: my thinking is that gitignore pertains to the push-to-remote; I can commit whatever, and locally that will be fine, but whatever is in gitignore will not be pushed. Perhaps I misunderstand gitignore.

So here's the git status after running main.py without making any changes to everything else in the uwlswd repo:

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   py/__pycache__/serialize.cpython-38.pyc

Where I'm at now: I'm inclined to just enter:
 git restore py/__pycache__/serialize.cpython-38.pyc
...thereby doing something akin to delting my changes to that pyc file.

Yes?

**Comment by briesenberg07** [comment]
@gerontakos will you try...

```
> git pull
> git rm -r --cached __pycache__
> git status
```

and then see whether git is still talking about `__pycache__`?  

I'm working from the top-voted answer to [this StackOverflow question](https://stackoverflow.com/questions/1470572/ignoring-any-bin-directory-on-a-git-project)
